# Site settings
title: Compix Infotech
email: info@compix.in
description: We're currently working on creating something fantastic. #We're all different. [indicates Mr. Fox] Especially him. But there's something kind of fantastic about that, isn't there?
baseurl: '/compix' # the subpath of your site, e.g. /blog
url: 'http://compix.in' # the base hostname & protocol for your site

author:
  name: 'Compix'
  email: Info@compix.in
  twitter_username: compix_infotech
  facebook_username: joshgerdes
  github_username:  joshgerdes
  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Social settings
github_url: https://github.com/CompixGit
# gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
# instagram_url:
# linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
# pinterest_url:
# slack_url:
twitter_url: https://twitter.com/Compix_Infotech

# Build settings
destination: _site
# paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

# plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
